default_stages: [commit]
fail_fast: false
default_language_version:
  python: python3.7
exclude: '.devcontainer'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.11b1]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.920
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
          [types-requests, types-PyYAML, pytest-mypy-plugins, pydantic]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types: [javascript]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - eslint@8.3.0
          - eslint-config-google@latest
          - eslint-config-prettier
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
