@hostname = host.docker.internal
@port = 31950
@host = http://{{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@header = opentrons-version: *
@runId = fd0983a4-5d5c-4f88-9925-7ea5422140ee
@binary = true

GET {{host}}/health
opentrons-version: *

###
POST {{host}}/robot/lights
opentrons-version: *

{"on": "{{binary}}" }


###
GET {{host}}/runs
opentrons-version: *
Content-Type: {{contentType}}

###
# Create a run
POST {{host}}/runs
opentrons-version: *
Content-Type: application/json

{
  "data": {}
}

###
GET {{host}}/runs/{{runId}}/commands
opentrons-version: *

###

POST {{host}}/runs/{{runId}}/commands
opentrons-version: *
Content-Type: application/json

{
    "data": {
        "commandType": "setRailLights",
        "params": {
            "on": true
        }
    }
}

###
GET {{host}}/modules
opentrons-version: *

###

POST {{host}}/runs/{{runId}}/commands
opentrons-version: *
Content-Type: application/json

{
    "data": {
        "commandType": "loadModule",
        "params": {
            "model": "magneticModuleV1",
            "location": {
                "slotName": "3"
            }
        }
    }
}
